build_validate_enabled_flag(BUILD_opencv_python2)
build_validate_disabled_or_undefined_flag(BUILD_opencv_python3)

build_validate_disabled_or_undefined_flag(ANDROID)

build_validate_enabled_flag(ENABLE_NEON)
