if(CMAKE_SYSTEM_PROCESSOR STREQUAL "armv7-a")
  include("${CMAKE_CURRENT_LIST_DIR}/details/check_compiler_options-armv7a.cmake")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
  include("${CMAKE_CURRENT_LIST_DIR}/details/check_compiler_options-aarch64.cmake")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "armv5te")
  include("${CMAKE_CURRENT_LIST_DIR}/details/check_compiler_options-armv5te.cmake")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  include("${CMAKE_CURRENT_LIST_DIR}/details/check_compiler_options-x86_64.cmake")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "i686")
  include("${CMAKE_CURRENT_LIST_DIR}/details/check_compiler_options-i686.cmake")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "mips64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "mips")
  # deprecated platform, no checks
else()
  message(WARNING "Unknown configuration: CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}")
  message(STATUS "CMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}")
  message(STATUS "CMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}")
  message(STATUS "CMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}")
endif()
